import { User } from '../../types/User';

export const usersFromServer: User[] = [
  {
    id: 0,
    name: 'Viktoria',
    surname: 'Bavorovska',
    nickname: 'Viki',
    score: 999,
    imgUrl: 'img/users/user-0',
  },
  {
    id: 1,
    name: 'John',
    surname: 'Doe',
    nickname: 'JD',
    score: 800,
  },
  {
    id: 2,
    name: 'Alice',
    surname: 'Johnson',
    nickname: 'Ali',
    score: 750,
  },
  {
    id: 3,
    name: 'Daniel',
    surname: 'Brown',
    nickname: 'Dan',
    score: 920,
  },
  {
    id: 4,
    name: 'Emily',
    surname: 'Williams',
    nickname: 'Emi',
    score: 850,
  },
  {
    id: 5,
    name: 'William',
    surname: 'Jones',
    nickname: 'Will',
    score: 880,
  },
  {
    id: 6,
    name: 'Olivia',
    surname: 'Davis',
    nickname: 'Liv',
    score: 920,
  },
  {
    id: 7,
    name: 'Liam',
    surname: 'Miller',
    nickname: 'Lee',
    score: 760,
  },
  {
    id: 8,
    name: 'Sophie',
    surname: 'Anderson',
    nickname: 'Soph',
    score: 910,
  },
  {
    id: 9,
    name: 'Aiden',
    surname: 'Thompson',
    nickname: 'Aid',
    score: 780,
  },
  {
    id: 10,
    name: 'Mia',
    surname: 'Martin',
    nickname: 'Mimi',
    score: 930,
  },
  {
    id: 11,
    name: 'Ethan',
    surname: 'Cooper',
    nickname: 'Ethy',
    score: 870,
  },
  {
    id: 12,
    name: 'Ava',
    surname: 'Harris',
    nickname: 'Ave',
    score: 890,
  },
  {
    id: 13,
    name: 'Logan',
    surname: 'Evans',
    nickname: 'Lo',
    score: 800,
  },
  {
    id: 14,
    name: 'Emma',
    surname: 'Ward',
    nickname: 'Em',
    score: 940,
  },
  {
    id: 15,
    name: 'Noah',
    surname: 'Baker',
    nickname: 'N',
    score: 790,
  },
  {
    id: 16,
    name: 'Isabella',
    surname: 'Bell',
    nickname: 'Izzy',
    score: 910,
  },
  {
    id: 17,
    name: 'Lucas',
    surname: 'Smith',
    nickname: 'Lu',
    score: 830,
  },
  {
    id: 18,
    name: 'Aria',
    surname: 'Clark',
    nickname: 'Ari',
    score: 960,
  },
  {
    id: 19,
    name: 'Jackson',
    surname: 'King',
    nickname: 'Jack',
    score: 850,
  },
  {
    id: 20,
    name: 'Grace',
    surname: 'Turner',
    nickname: 'Gra',
    score: 920,
  },
  {
    id: 21,
    name: 'Carter',
    surname: 'Roberts',
    nickname: 'Car',
    score: 800,
  },
  {
    id: 22,
    name: 'Chloe',
    surname: 'Wright',
    nickname: 'Clo',
    score: 930,
  },
  {
    id: 23,
    name: 'Henry',
    surname: 'Parker',
    nickname: 'Hank',
    score: 870,
  },
  {
    id: 24,
    name: 'Lily',
    surname: 'Hayes',
    nickname: 'Lil',
    score: 910,
  },
];
